feat: the aspects code work, but i will make it clean later
learnery-engine/creator.learnery pull request #23
Opened 2023-08-04 17:52 UTC by aldoprogrammer

## Related Issue(s)

[//]: # ([Cite any related issue&#40;s&#41; or feature request&#40;s&#41; from the repository's issue tracker.])
Fixes #
For #

## Proposed Changes

[//]: # ([List down the specific changes you have made in this pull request.])

- [x]
- [x]

## Checklist

- [x] I have followed the repository's contribution guidelines.
- [x] I have added necessary documentation or updated existing documentation.
- [x] My code follows the established code style and formatting of the project.
- [x] I have tested my changes and they function as expected.
- [ ] I have added suitable unit tests (if applicable).

## Screenshots

## To-Do

- [ ] 

## Additional Information

2023-08-04 19:55 UTC, Nasfame requested changes

2023-08-04 19:55 UTC, Nasfame commented on next.config.js
> +    // output: 'export',
why disable it? Where r using nextjs exclusively for frontend only

2023-08-04 21:21 UTC, Nasfame commented
@aldoprogrammer fix the vercel logs. I hope u r able to access the logs!!

2023-08-05 00:10 UTC, aldoprogrammer commented on next.config.js
> +    // output: 'export',
bcs if i dont disable it, the code itself won't work on my machine. i tried to debug it, and found on the internet to remvoe that line, that's why i commented it. and if i dont commeneted it, it wont work on my machine.

2023-08-05 01:16 UTC, aldoprogrammer commented
> @aldoprogrammer fix the vercel logs. I hope u r able to access the logs!!

I'll fix everything later on

2023-08-05 01:26 UTC, aldoprogrammer commented on next.config.js
> +    // output: 'export',
I fixed it now, but adding the images: { unoptimized: true }, and not comenting the output anymore, tht is the only two choices which the nextjs itself gives an error to fixed it when i tried to run the code

2023-08-05 03:44 UTC, Nasfame commented on next.config.js
> +    // output: 'export',
ok since we are on vercel we can support SSR. So no worries of static builds. But fix the rest of issues in vercel deployment

2023-08-05 15:32 UTC, Nasfame commented
@aldoprogrammer 

I would advice u to follow a  next13 tutorial. 
- Understand routing in next13
- Build apis in nextJS



We are turning down this pr cuz u have invalid code in a NextJS Project. For instance,  usage of React router is not required.

2023-08-05 15:32 UTC, closed without merging

2023-08-06 11:33 UTC, aldoprogrammer commented
@Nasfame Sure, I am so sorry for this mess cause I haven't learned the next js to be honest, only react js before this. But,now I already watch some Next js tutorial, and hopefuly will not making any mess anymore in this project. 

Anyway, the todos in nextjs13 app you asked me for already done, i already give the link in the attlassian.